blank_issues_enabled: false
contact_links:
  - name: 📖 Documentation
    url: https://github.com/yuvraj-rathod-1202/event-hub-unify/blob/main/README.md
    about: Check our documentation for setup and usage instructions
  - name: 🚀 Live Demo
    url: https://event-hub-unify.vercel.app/
    about: Try out the live application
